import { expect, test, type Page } from '@playwright/test'
const actions = (page: Page) => page.evaluate(() => (window as unknown as { captureTestActions?: { action: string; payload: { value?: string; rect?: { x: number; y: number; width: number; height: number } } }[] }).captureTestActions ?? [])
async function select(page: Page, query = '') {
  await page.setViewportSize({ width: 1280, height: 800 }); await page.goto(`/?capture-lab=1${query}`)
  await expect(page.locator('.jt-chrome')).toBeVisible()
  await page.mouse.move(160, 150); await page.mouse.down(); await page.mouse.move(720, 450); await page.mouse.up()
}
async function scan(page: Page) {
  await page.getByRole('button', { name: '更多工具', exact: true }).click()
  await page.getByRole('button', { name: '扫描二维码 / 条形码', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '扫码结果', exact: true })).toBeVisible()
}
test('pin preparation failure restores original editing and does not hide selected pixels', async ({ page }) => {
  await select(page, '&fail-pin=1')
  const pixels = await page.locator('.jt-document').evaluate((c: HTMLCanvasElement) => c.toDataURL())
  await page.getByRole('button', { name: '钉图', exact: true }).click()
  await expect(page.getByRole('button', { name: '钉图', exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('钉图加载失败')
  expect(await page.locator('.jt-document').evaluate((c: HTMLCanvasElement) => c.toDataURL())).toBe(pixels)
  expect((await actions(page)).some(a => a.action === 'pin_abort')).toBe(true)
  expect((await actions(page)).some(a => a.action === 'dismiss')).toBe(false)
  await expect(page.locator('.jt-physical-stage')).toHaveCSS('clip-path', 'none')
})
test('selected canvas and controls stay intact until identical native pixels are acknowledged', async ({ page }) => {
  await select(page, '&slow-pin-prepare=1&slow-pin=1')
  const pixels = await page.locator('.jt-document').evaluate((c: HTMLCanvasElement) => c.toDataURL())
  await page.getByRole('button', { name: '钉图', exact: true }).click()
  await expect.poll(() => page.evaluate(() => typeof (window as unknown as { resolveCapturePinPrepare?: () => void }).resolveCapturePinPrepare)).toBe('function')
  await expect(page.locator('.jt-physical-stage')).toHaveCSS('clip-path', 'none')
  await expect(page.getByRole('toolbar', { name: '截图工具条' })).toBeVisible()
  expect(await page.locator('.jt-document').evaluate((c: HTMLCanvasElement) => c.toDataURL())).toBe(pixels)
  const prepared = await page.evaluate(() => (window as unknown as { captureTestActions: { action: string; payload: { image?: string } }[] }).captureTestActions.find(a => a.action === 'pin_prepare')?.payload.image)
  expect(prepared).toMatch(/^data:image\/png;base64,/u)
  expect((await actions(page)).some(a => a.action === 'pin')).toBe(false)
  await page.evaluate(() => { (window as unknown as { resolveCapturePinPrepare: () => void }).resolveCapturePinPrepare() })
  await expect(page.locator('.jt-toolbar, .jt-selection-info, .jt-magnifier')).toHaveCount(0)
  expect(await page.locator('.jt-document').evaluate((c: HTMLCanvasElement) => c.toDataURL())).toBe(pixels)
  expect((await actions(page)).some(a => a.action === 'dismiss')).toBe(false)
})
test('pin ignores transforms until the actual painted image has been acknowledged', async ({ page }) => {
  await page.goto('/?capture-lab=1&mode=pin&pin-width=480&pin-height=320&slow-pin-paint=1')
  const picture = page.locator('.jt-pin-image')
  await expect(picture).toBeVisible()
  await expect.poll(() => page.evaluate(() => typeof (window as unknown as { resolveCapturePinPresented?: () => void }).resolveCapturePinPresented)).toBe('function')
  const before = await picture.boundingBox()
  await picture.hover(); await page.mouse.wheel(0,-100); await page.keyboard.press('Control+c')
  expect(await picture.boundingBox()).toEqual(before)
  expect((await actions(page)).some(a => a.action === 'copy')).toBe(false)
  await page.evaluate(() => { (window as unknown as { resolveCapturePinPresented: () => void }).resolveCapturePinPresented() })
  await page.keyboard.press('Control+c')
  await expect.poll(async () => (await actions(page)).some(a => a.action === 'copy')).toBe(true)
  await picture.hover(); await page.mouse.wheel(0,-100)
  await expect.poll(async () => (await picture.boundingBox())?.width ?? 0).toBeGreaterThan(before?.width ?? 0)
})
test('pin retention includes the original selection frame without file export padding', async ({ page }) => {
  await select(page, '&decorated-pin=1&slow-pin=1')
  await page.getByRole('button', { name: '钉图', exact: true }).click()
  await expect.poll(async () => (await actions(page)).some(a => a.action === 'pin')).toBe(true)
  const pixels = await page.evaluate(async () => {
    const calls = (window as unknown as { captureTestActions: { action: string; payload: { image?: string } }[] }).captureTestActions
    const decode = async (src?: string) => { const image = new Image(); image.src = src ?? ''; await image.decode(); const c = document.createElement('canvas'); c.width = image.width; c.height = image.height; c.getContext('2d')?.drawImage(image,0,0); return { size:[image.width,image.height], alpha:c.getContext('2d')?.getImageData(0,0,1,1).data[3] } }
    return [await decode(calls.find(a=>a.action==='pin_prepare')?.payload.image),await decode(calls.find(a=>a.action==='pin')?.payload.image)]
  })
  expect(pixels[0]).toEqual({ size:[566,306],alpha:0 })
  expect(pixels[1]?.size).toEqual([576,316])
})
test('scan exits capture and opens a nearby translator-style popup with the same jelly arrival and clickable embedded links', async ({ page }) => {
  await select(page, '&multi-scan=1'); await scan(page)
  await expect(page.locator('.jt-surface')).toHaveCount(0)
  const popup = page.getByRole('dialog', { name: '扫码结果' })
  await expect(popup).toHaveClass(/ocr-result-card.*screenpilot-jelly-pop/u)
  await expect(popup).toHaveCSS('animation-name', 'screenpilot-translator-arrive')
  await expect(popup).toHaveCSS('animation-duration', '0.36s')
  await expect(popup).toHaveCSS('border-radius', '16px')
  await expect(popup.getByLabel('识别结果 2')).toHaveText('6901234567890')
  const calls = await actions(page)
  expect(calls.findIndex(a => a.action === 'dismiss')).toBeLessThan(calls.findIndex(a => a.action === 'scan'))
  expect(calls.find(a => a.action === 'scan')?.payload.rect).toEqual({ x: 160, y: 150, width: 560, height: 300 })
  await popup.evaluate(async e => { await Promise.all(e.getAnimations().map(a => a.finished)) })
  const box = await popup.boundingBox(); if (!box) throw new Error('Missing result popup')
  expect(box.x).toBeGreaterThanOrEqual(160); expect(box.x + box.width).toBeLessThanOrEqual(1280)
  expect(box.y).toBe(150)
  const link = popup.getByRole('link', { name: 'https://example.com/help', exact: true })
  await link.click()
  await expect.poll(async () => (await actions(page)).filter(a => a.action === 'open_link').at(-1)?.payload.value).toBe('https://example.com/help')
  await popup.getByRole('link', { name: 'www.example.org', exact: true }).click()
  await expect.poll(async () => (await actions(page)).filter(a => a.action === 'open_link').at(-1)?.payload.value).toBe('https://www.example.org')
  await popup.getByRole('button', { name: '复制结果 1' }).click()
  await expect(popup.locator('.ocr-result-status')).toHaveText('已复制')
  await page.screenshot({ path: '.task/capture-scan-popup.png', animations: 'disabled' })
  await popup.getByRole('button', { name: '关闭扫码结果' }).click()
  await expect(popup).toHaveCount(0)
})
test('scan loading and empty results remain independent of capture and can close with Escape', async ({ page }) => {
  await select(page, '&slow-scan=1&empty-scan=1'); await scan(page)
  await expect(page.getByRole('status')).toContainText('正在识别二维码')
  await expect(page.locator('.jt-surface')).toHaveCount(0)
  await page.evaluate(() => { (window as unknown as { resolveCaptureScan: () => void }).resolveCaptureScan() })
  await expect(page.getByRole('dialog')).toContainText('没有识别到二维码或条形码')
  await expect(page.getByRole('button', { name: '重新扫码' })).toBeVisible()
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0)
})
test('scan copy errors use the global top notice, with no full-screen capture overlay', async ({ page }) => {
  await select(page, '&fail-copy=1'); await scan(page)
  await page.getByRole('button', { name: '复制结果 1' }).click()
  const alert = page.getByRole('alert')
  await expect(alert).toContainText('剪贴板正忙')
  await expect(alert.locator('.save-success-toast')).toHaveCSS('border-radius', '10px')
  await alert.getByRole('button', { name: '关闭提示' }).click(); await expect(alert).toHaveCount(0)
  await expect(page.getByRole('dialog', { name: '扫码结果' })).toBeVisible()
  await expect(page.locator('.jt-surface')).toHaveCount(0)
})
