import { test, expect, type Page } from '@playwright/test'

const shapeLabel = '形状（矩形 / 椭圆）'
async function select(page: Page) {
  await expect(page.locator('.jt-chrome')).toBeVisible()
  await page.mouse.move(160, 120); await page.mouse.down(); await page.mouse.move(1000, 540); await page.mouse.up()
  await expect(page.getByRole('toolbar', { name: '截图工具条' })).toBeVisible()
}
const documentPixels = (page: Page) => page.locator('.jt-document').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
const chromePixels = (page: Page) => page.locator('.jt-chrome').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
const actions = (page: Page) => page.evaluate(() => (window as unknown as { captureTestActions: { action: string; payload?: unknown }[] }).captureTestActions)

test.beforeEach(async ({ page }) => { await page.setViewportSize({ width: 1280, height: 800 }); await page.goto('/?capture-lab=1') })

test('retired highlighter stays absent and download is immediately left of copy with the new glyphs', async ({ page }) => {
  await select(page)
  const toolbar = page.getByRole('toolbar', { name: '截图工具条' })
  const order = await toolbar.locator('.jt-tool').evaluateAll(elements => elements.map(element => element.getAttribute('data-tool')))
  expect(order.slice(-2)).toEqual(['save', 'confirm'])
  expect(order).not.toContain('highlighter')
  expect(order[order.indexOf('gif') + 1]).toBe('spotlight')
  const gifSource = await toolbar.locator('[data-tool=gif] img').getAttribute('src'), spotlightSource = await toolbar.locator('[data-tool=spotlight] img').getAttribute('src')
  if (!gifSource || !spotlightSource) throw new Error('Expected the original GIF and spotlight icons')
  await expect.poll(() => toolbar.locator('[data-tool=gif] img, [data-tool=spotlight] img').evaluateAll(images => images.every(image => image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0))).toBe(true)
  await expect(toolbar.getByRole('button', { name: '保存到文件', exact: true }).locator('svg')).toHaveClass(/lucide-download/u)
  await expect(toolbar.locator('[data-tool=mosaic] svg')).toHaveAttribute('data-capture-icon', 'mosaic')
  await expect(toolbar.locator('[data-tool=arrow] svg')).toHaveAttribute('data-capture-icon', 'tapered-arrow')
  await page.keyboard.press('p'); await page.keyboard.press('m')
  await expect(toolbar.getByRole('button', { name: '画笔（Shift 直线）' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('spinbutton', { name: '线宽', exact: true })).toHaveValue('12')
  await page.getByRole('button', { name: '更多工具' }).click(); await page.getByRole('button', { name: '调整工具栏…' }).click()
  const dialog = page.getByRole('dialog', { name: '调整工具栏' })
  await expect(dialog).not.toContainText('荧光笔')
  const gifRow = dialog.locator('.jt-layout-list > div').filter({ has: page.getByText('GIF / 视频录制', { exact: true }) })
  const spotlightRow = dialog.locator('.jt-layout-list > div').filter({ has: page.getByText('聚光灯', { exact: true }) })
  const copyRow = dialog.locator('.jt-layout-list > div').filter({ has: page.getByText('完成并复制 Enter', { exact: true }) })
  await expect(gifRow.locator('img')).toHaveAttribute('src', gifSource)
  await expect(spotlightRow.locator('img')).toHaveAttribute('src', spotlightSource)
  await expect(copyRow.locator('svg')).toHaveClass(/lucide-copy/u)
  expect(await copyRow.locator('svg').evaluate(element => element.outerHTML)).toBe(await toolbar.locator('[data-tool=confirm] svg').evaluate(element => element.outerHTML))
  await expect(spotlightRow.getByRole('button', { name: '上移聚光灯', exact: true })).toBeDisabled()
  await gifRow.getByRole('button', { name: '下移GIF / 视频录制', exact: true }).click()
  const updated = await toolbar.locator('.jt-tool').evaluateAll(elements => elements.map(element => element.getAttribute('data-tool')))
  expect(updated.indexOf('pen')).toBeLessThan(updated.indexOf('gif')); expect(updated[updated.indexOf('gif') + 1]).toBe('spotlight')
  await expect(dialog.getByRole('button', { name: '上移保存到文件', exact: true })).toBeDisabled()
  await page.screenshot({ path: '.task/capture-drawing-layout-icons.png' })
  await dialog.getByRole('button', { name: '完成', exact: true }).click()
  await page.screenshot({ path: '.task/capture-toolbar-icon-refinement.png' })
})

test('one shape menu preserves independent styles, shortcut selection and Escape without cancelling capture', async ({ page }) => {
  await select(page)
  const toolbar = page.getByRole('toolbar', { name: '截图工具条' }), shape = toolbar.getByRole('button', { name: shapeLabel, exact: true })
  await expect(toolbar.locator('[data-tool=rect], [data-tool=ellipse]')).toHaveCount(0)
  await expect(shape).toHaveCount(1)
  await shape.click(); await expect(page.getByRole('menu', { name: '选择形状' })).toBeVisible()
  await page.screenshot({ path: '.task/capture-shape-menu.png' })
  await page.getByRole('menuitemradio', { name: '矩形（Shift 正方形）', exact: true }).click()
  await expect(shape).toHaveAttribute('aria-pressed', 'true')
  const width = page.getByRole('spinbutton', { name: '线宽', exact: true })
  await width.fill('4')
  await page.mouse.move(260, 240); await page.mouse.down(); await page.mouse.move(600, 380); await page.mouse.up()
  await shape.click(); await page.getByRole('menuitemradio', { name: '椭圆（Shift 正圆）', exact: true }).click()
  await expect(width).toHaveValue('9'); await width.fill('7')
  await width.blur(); await page.keyboard.press('r'); await expect(width).toHaveValue('4')
  await page.keyboard.press('o'); await expect(width).toHaveValue('7')
  await shape.click(); await page.keyboard.press('Escape')
  await expect(page.getByRole('menu', { name: '选择形状' })).toHaveCount(0)
  expect((await actions(page)).some(action => action.action === 'cancel')).toBe(false)
  await shape.focus(); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Home'); await page.keyboard.press('Enter')
  await expect(width).toHaveValue('4'); expect((await actions(page)).some(action => action.action === 'confirm')).toBe(false)
  await shape.click(); await page.mouse.click(900, 490); await expect(shape).toHaveAttribute('aria-expanded', 'false')
  await expect(toolbar.getByRole('button', { name: '画笔（Shift 直线）' }).locator('svg')).toHaveClass(/lucide-pen/u)
  await expect(toolbar.locator('.lucide-paintbrush')).toHaveCount(0)
})

test('drawing on existing shapes and former handles adds marks without a frame; only Ctrl moves them', async ({ page }) => {
  await page.goto('/?capture-lab=1&no-cross-tool=1'); await select(page)
  await page.keyboard.press('r')
  const chrome = await chromePixels(page)
  await page.mouse.move(260, 240); await page.mouse.down(); await page.mouse.move(600, 380); await page.mouse.up()
  const before = await documentPixels(page)
  await expect.poll(() => chromePixels(page)).toBe(chrome)
  await page.mouse.move(310, 240); await page.mouse.down(); await page.mouse.move(335, 255); await page.mouse.up()
  await expect.poll(() => documentPixels(page)).not.toBe(before)
  await page.keyboard.press('Control+z'); await expect.poll(() => documentPixels(page)).toBe(before)
  await expect(page.locator('.jt-selection-info')).toContainText('840 × 420')
  // The former frame position now starts a new shape instead of moving the old one.
  await page.mouse.move(310, 237); await page.mouse.down(); await page.mouse.move(335, 252); await page.mouse.up()
  await expect.poll(() => documentPixels(page)).not.toBe(before)
  await page.keyboard.press('Control+z'); await expect.poll(() => documentPixels(page)).toBe(before)
  await page.mouse.move(260, 240); await page.mouse.down(); await page.mouse.move(300, 270); await page.mouse.up()
  await expect.poll(() => documentPixels(page)).not.toBe(before)
  await page.keyboard.press('Control+z'); await expect.poll(() => documentPixels(page)).toBe(before)
  await page.keyboard.press('p')
  await page.keyboard.down('Control'); await page.mouse.move(310, 240); await page.mouse.down(); await page.mouse.move(335, 255); await page.mouse.up(); await page.keyboard.up('Control')
  await expect.poll(() => documentPixels(page)).not.toBe(before)
  await page.keyboard.press('Control+z'); await expect.poll(() => documentPixels(page)).toBe(before)
  await expect(page.locator('.jt-selection-info')).toContainText('840 × 420')
})

test('pen continues from a previous stroke endpoint and middle with independent undo', async ({ page }) => {
  await select(page); await page.keyboard.press('p')
  const chrome = await chromePixels(page)
  await page.mouse.move(300, 280); await page.mouse.down(); await page.mouse.move(500, 360); await page.mouse.up()
  const first = await documentPixels(page)
  for (const start of [{ x: 500, y: 360 }, { x: 400, y: 320 }]) {
    await page.mouse.move(start.x, start.y); await page.mouse.down(); await page.mouse.move(660, 280); await page.mouse.up()
    await expect.poll(() => documentPixels(page)).not.toBe(first)
    const second = await documentPixels(page)
    await expect.poll(() => chromePixels(page)).toBe(chrome)
    await page.keyboard.press('Control+z'); await expect.poll(() => documentPixels(page)).toBe(first)
    await page.keyboard.press('Control+y'); await expect.poll(() => documentPixels(page)).toBe(second)
    await page.keyboard.press('Control+z'); await expect.poll(() => documentPixels(page)).toBe(first)
  }
  await page.screenshot({ path: '.task/capture-drawing-no-frame.png' })
})

test('magnifier draws a grid by default and still honors a saved off setting', async ({ page }) => {
  await expect(page.locator('.jt-chrome')).toBeVisible()
  await page.mouse.move(700, 430); await expect(page.locator('.jt-magnifier')).toBeVisible()
  await expect(page.locator('.jt-magnifier-position')).toHaveText('(700, 430)')
  const pixels = () => page.locator('.jt-magnifier canvas').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
  const enabled = await pixels()
  await page.screenshot({ path: '.task/capture-shape-grid-default.png' })
  await page.goto('/?capture-lab=1&grid-off=1'); await expect(page.locator('.jt-chrome')).toBeVisible(); await page.mouse.move(700, 430)
  await expect(page.locator('.jt-magnifier')).toBeVisible()
  await expect(page.locator('.jt-magnifier-position')).toHaveText('(700, 430)')
  await expect.poll(pixels).not.toBe(enabled)
})

test('shape popup and combined glyph fit small screens at each toolbar scale and DPI', async ({ browser }) => {
  for (const ratio of [1, 1.25, 1.5, 2]) {
    const context = await browser.newContext({ viewport: { width: 800, height: 720 }, deviceScaleFactor: ratio })
    const page = await context.newPage()
    for (const scale of [80, 100, 150, 200]) {
      await page.goto(`/?capture-lab=1&scale=${scale}`); await expect(page.locator('.jt-chrome')).toBeVisible()
      await page.mouse.move(180, 100); await page.mouse.down(); await page.mouse.move(780, 660); await page.mouse.up()
      const trigger = page.getByRole('button', { name: shapeLabel, exact: true }); await trigger.click()
      const menu = page.getByRole('menu', { name: '选择形状' }); await expect(menu).toBeVisible()
      const box = await menu.boundingBox(); expect(box).not.toBeNull()
      expect(box?.x).toBeGreaterThanOrEqual(0); expect(box && box.x + box.width).toBeLessThanOrEqual(800)
      expect(box?.y).toBeGreaterThanOrEqual(0); expect(box && box.y + box.height).toBeLessThanOrEqual(720)
      const glyphs = await trigger.evaluate(element => [...element.querySelectorAll('svg')].map(svg => { const r = svg.getBoundingClientRect(), b = element.getBoundingClientRect(); return r.x >= b.x && r.right <= b.right && r.y >= b.y && r.bottom <= b.bottom }))
      expect(glyphs).toEqual([true, true])
      await page.getByRole('menuitemradio', { name: '椭圆（Shift 正圆）', exact: true }).click()
      await expect(trigger).toHaveAttribute('aria-pressed', 'true')
      if (ratio === 1.5 && scale === 150) await page.screenshot({ path: '.task/capture-shape-toolbar-dpi150.png' })
    }
    await context.close()
  }
})

test('pins and recording share the grouped shape picker and pen icon', async ({ page }) => {
  await page.goto('/?capture-lab=1&mode=pin'); await expect(page.locator('.jt-pin-image')).toBeVisible(); await page.keyboard.press('Space')
  await page.getByRole('button', { name: shapeLabel, exact: true }).click()
  // R retains the pin's existing thumbnail shortcut, so do not claim it draws a rectangle.
  await expect(page.getByRole('menu', { name: '选择形状' }).locator('kbd')).toHaveText(['', ''])
  await page.getByRole('menuitemradio', { name: '椭圆（Shift 正圆）', exact: true }).click()
  await expect(page.getByRole('button', { name: shapeLabel, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.goto('/?capture-lab=1&mode=record'); await expect(page.locator('.jt-chrome')).toBeVisible()
  await page.mouse.move(160, 120); await page.mouse.down(); await page.mouse.move(1000, 540); await page.mouse.up()
  const toolbar = page.getByRole('toolbar', { name: '录制工具条' })
  await toolbar.getByRole('button', { name: shapeLabel, exact: true }).click()
  await page.getByRole('menuitemradio', { name: '矩形（Shift 正方形）', exact: true }).click()
  await expect(toolbar.locator('[data-tool=rect], [data-tool=ellipse]')).toHaveCount(0)
  await expect(toolbar.getByRole('button', { name: '画笔（Shift 直线）' }).locator('svg')).toHaveClass(/lucide-pen/u)
})
