import type { InterfaceLanguage, TranslationLanguage, TranslationMethod } from '../features/settings/types'

const zh = {
  unknownError: '未知错误',
  retry: '重试',
  close: '关闭',
  save: '保存',
  saving: '保存中…',
  cancel: '取消',
  resetDefault: '恢复默认',
  noSelection: '未选择',
  auto: '自动',
  autoDetect: '自动判断',
  followInput: '跟随原文',
  followQuestion: '跟随问题',
  simplifiedChinese: '简体中文',
  english: 'English',
  japanese: '日本語',
  korean: '한국어',
  themeSystem: '系统',
  themeLight: '浅色',
  themeDark: '深色',
  navGeneral: '常规',
  navTranslation: '翻译',
  navScreenshot: 'OCR',
  navVision: 'Vision',
  navOptimizer: '提示词优化',
  navProviders: '模型提供商',
  navAbout: '关于',
  settingsSections: '设置分区',
  currentPermission: '当前运行权限',
  permissionChecking: '权限：检测中',
  permissionFailed: '权限：检测失败',
  permissionAdministrator: '权限：管理员',
  permissionStandard: '权限：普通用户',
  unsavedChanges: '有未保存更改',
  allChangesSaved: '所有更改已保存',
  closeSettings: '关闭设置',
  settingsLoadFailed: '无法加载设置',
  settingsLoading: '正在加载设置',
  settingsSaved: '设置已保存并立即生效',
  settingsLoadedPendingSave: '配置已载入，保存后才会应用',
  settingsExported: '配置已导出',
  directoryPickFailed: '选择目录失败',
  settingsExportFailed: '配置导出失败',
  settingsImportFailed: '配置导入失败',
  saveFailed: '保存失败',
  credentialSaveFailed: '凭据保存失败',
  settingsRollbackFailed: '设置回滚失败',
  closeAfterSavingTitle: '保存更改后关闭？',
  closeAfterSavingBody: '未保存的设置不会生效。',
  saveAndClose: '保存并关闭',
  discardChanges: '放弃更改',
  continueEditing: '继续编辑',
  importOverwriteTitle: '覆盖当前未保存内容？',
  importOverwriteBody: '导入会替换当前编辑中的设置，但仍需点击保存才会应用。',
  continueImport: '继续导入',
  appearanceAndLanguage: '外观与语言',
  theme: '主题',
  interfaceLanguage: '界面语言',
  chinese: '中文',
  runtimeBehavior: '运行行为',
  automaticRetry: '自动重试',
  retryAttempts: '重试次数',
  autoPaste: '自动上屏',
  autoPasteDescription: '提交后等待约 600ms，再粘贴回原应用',
  launchAtStartup: '开机启动',
  launchAsAdministrator: '管理员身份',
  launchAsAdministratorDescription: '保存时 Windows 会请求 UAC 确认；开机启动时将以管理员权限运行',
  screenshotArchive: '截图自动归档',
  archiveDirectory: '归档目录',
  archiveDirectoryRequired: '启用截图自动归档前，请先选择归档目录',
  chooseDirectory: '选择目录',
  globalShortcuts: '全局快捷键',
  textTranslation: '文本翻译',
  screenshotTranslation: 'OCR翻译',
  promptOptimization: '提示词优化',
  recordTextTranslationShortcut: '录制文本翻译快捷键',
  recordVisionShortcut: '录制 Vision 快捷键',
  recordScreenshotShortcut: '录制OCR翻译快捷键',
  recordOptimizerShortcut: '录制提示词优化快捷键',
  pressShortcut: '请按快捷键',
  translationBehavior: '翻译行为',
  sourceLanguage: '源语言',
  targetLanguage: '目标语言',
  enableAiTranslation: '开启大模型翻译',
  aiModel: 'AI 模型',
  textTranslationAiModel: '文本翻译 AI 模型',
  translationInterface: '翻译接口',
  aiTranslationSystemPrompt: '大模型翻译系统提示词',
  enableScreenshotTranslation: '启用OCR翻译',
  screenshotTargetLanguage: 'OCR翻译目标语言',
  screenshotSourceLanguage: 'OCR翻译源语言',
  enableAiOcr: '开启大模型 OCR',
  ocrModel: 'OCR 模型',
  ocrInterface: 'OCR 接口',
  aiVisionOcr: 'AI 视觉 OCR',
  baiduOcr: '百度 OCR',
  chaoxingOcr: '学习通 OCR',
  screenshotTranslationModel: 'OCR翻译模型',
  screenshotTranslationInterface: 'OCR翻译接口',
  translationModel: '翻译模型',
  showRecognizedSource: '显示识别原文',
  streamingOutput: '流式输出',
  screenshotStreamingOutput: 'OCR翻译流式输出',
  showReasoning: '显示思考过程',
  reasoningEffort: '思考强度',
  screenshotReasoningEffort: 'OCR翻译思考强度',
  ocrPrompt: 'OCR 提示词',
  screenshotTranslationPrompt: 'OCR翻译提示词',
  credentialGroup: '接口凭据',
  credentialSaved: '凭据已安全保存',
  credentialRequired: '请完整填写凭据后再保存',
  visionQa: 'Vision 问答',
  enableVision: '启用 Vision',
  responseLanguage: '回答语言',
  visionResponseLanguage: 'Vision 回答语言',
  model: '模型',
  visionModel: 'Vision 模型',
  visionStreamingOutput: 'Vision 流式输出',
  visionReasoning: '显示思考过程/摘要',
  visionReasoningLabel: 'Vision 显示思考过程/摘要',
  visionReasoningEffort: 'Vision 思考强度',
  webSearch: '联网搜索',
  messageOrder: '消息顺序',
  oldMessagesFirst: '旧消息在上',
  newMessagesFirst: '新消息在上',
  systemPrompt: '系统提示词',
  visionSystemPrompt: 'Vision 系统提示词',
  questionPrompt: '问答提示词',
  visionQuestionPrompt: 'Vision 问答提示词',
  enableOptimizer: '启用优化器',
  enablePromptOptimizer: '启用提示词优化器',
  outputLanguage: '输出语言',
  optimizerOutputLanguage: '优化器输出语言',
  optimizerModel: '提示词优化模型',
  optimizerReasoningEffort: '提示词优化思考强度',
  optimizerSystemPrompt: '优化器系统提示词',
  optimizationPrompt: '优化提示词',
  configurationManagement: '配置管理',
  exportWithApiKeys: '导出时包含 API Key',
  exportWithApiKeysDescription: '默认关闭；开启后导出文件将包含敏感信息',
  exportIncludesApiKeys: '导出包含 API Key',
  exportConfiguration: '导出配置',
  importConfiguration: '导入配置',
  localOnlyFootnote: 'ScreenPilot 在本机处理设置与历史元数据，不提供账号或云端同步。',
  providersTitle: '模型提供商',
  providersDescription: '密钥保存在 Windows 凭据管理器，不写入设置文件。',
  add: '新增',
  noProviders: '尚未添加模型提供商',
  noProvidersDescription: '添加 OpenAI 兼容端点后，可分别为翻译、Vision 和优化器选择模型。',
  unnamedProvider: '未命名提供商',
  name: '名称',
  providerName: '提供商名称',
  providerBaseUrl: '提供商 Base URL',
  oneKeyPerLine: '每行一个密钥',
  fetchModels: '拉取模型',
  modelsFetched: '获取到 {count} 个模型',
  connectionSucceeded: '连接成功',
  connectionFailed: '连接失败',
  testConnection: '测试连接',
  deleteProvider: '删除 {name}',
  manualModelName: '{name} 手动模型名',
  manualModelPlaceholder: '手动添加模型，例如 local:vision',
  addModel: '添加',
  modelList: '{name} 模型列表',
  savedKeyCount: '已安全保存 {count} 个密钥',
  translatorTitle: '文本翻译',
  translating: '翻译中…',
  submitShortcut: 'Ctrl+Enter 提交',
  waitingForInput: '等待输入',
  translationHistory: '翻译历史',
  closeTranslator: '关闭翻译',
  originalText: '原文',
  translatorInputPlaceholder: '输入或通过 F2 获取当前选中文本',
  resizeTranslationPanels: '调整原文和译文高度',
  translatedText: '译文',
  copyTranslation: '复制译文',
  copyFailed: '复制失败，请检查剪贴板权限',
  translatedTextPlaceholder: '译文将在这里显示，可直接编辑',
  optimizerTitle: '提示词优化',
  optimizing: '优化中…',
  optimizeShortcut: 'Ctrl+Enter 优化',
  optimizationHistory: '优化历史',
  closeOptimizer: '关闭优化器',
  originalPrompt: '原始提示词',
  optimize: '优化',
  optimizerInputPlaceholder: '输入需要优化的提示词',
  resizeOptimizerPanels: '调整原始提示词和优化结果高度',
  optimizationResult: '优化结果',
  replaceOriginal: '替换原文',
  copyOptimizationResult: '复制优化结果',
  optimizationResultPlaceholder: '优化结果可在此编辑',
  historyCount: '历史记录：{count} 条',
  historyEmpty: '暂无历史记录',
  deleteHistory: '删除历史',
  clearHistory: '清空',
  justNow: '刚刚',
  minutesAgo: '{count} 分钟前',
  hoursAgo: '{count} 小时前',
  daysAgo: '{count} 天前',
  copyCode: '复制代码',
  send: '发送',
  translationFailed: '翻译失败',
  translatingToTarget: '正在按目标语言翻译…',
  duplicateProviderId: 'Provider ID 必须唯一',
  providerHttpsRequired: 'Provider URL 必须使用 HTTPS（本机地址除外）',
  providerUrlInvalid: 'Provider URL 无效',
  shortcutMissing: '快捷键不能为空',
  shortcutConflict: '快捷键存在冲突',
} as const

type UiCopy = { [K in keyof typeof zh]: string }

const en: UiCopy = {
  unknownError: 'Unknown error',
  retry: 'Retry',
  close: 'Close',
  save: 'Save',
  saving: 'Saving…',
  cancel: 'Cancel',
  resetDefault: 'Reset',
  noSelection: 'Not selected',
  auto: 'Auto',
  autoDetect: 'Auto detect',
  followInput: 'Follow input',
  followQuestion: 'Follow question',
  simplifiedChinese: 'Simplified Chinese',
  english: 'English',
  japanese: 'Japanese',
  korean: 'Korean',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  navGeneral: 'General',
  navTranslation: 'Translation',
  navScreenshot: 'OCR',
  navVision: 'Vision',
  navOptimizer: 'Prompt',
  navProviders: 'Providers',
  navAbout: 'About',
  settingsSections: 'Settings sections',
  currentPermission: 'Current permission',
  permissionChecking: 'Permission: checking',
  permissionFailed: 'Permission: unavailable',
  permissionAdministrator: 'Permission: administrator',
  permissionStandard: 'Permission: standard user',
  unsavedChanges: 'Unsaved changes',
  allChangesSaved: 'All changes saved',
  closeSettings: 'Close settings',
  settingsLoadFailed: 'Unable to load settings',
  settingsLoading: 'Loading settings',
  settingsSaved: 'Settings saved and applied',
  settingsLoadedPendingSave: 'Configuration loaded; save to apply it',
  settingsExported: 'Configuration exported',
  directoryPickFailed: 'Unable to choose directory',
  settingsExportFailed: 'Unable to export configuration',
  settingsImportFailed: 'Unable to import configuration',
  saveFailed: 'Save failed',
  credentialSaveFailed: 'Credential save failed',
  settingsRollbackFailed: 'Settings rollback failed',
  closeAfterSavingTitle: 'Save changes before closing?',
  closeAfterSavingBody: 'Unsaved settings will not take effect.',
  saveAndClose: 'Save & close',
  discardChanges: 'Discard changes',
  continueEditing: 'Continue editing',
  importOverwriteTitle: 'Replace unsaved changes?',
  importOverwriteBody: 'Importing replaces the settings being edited. Save afterwards to apply them.',
  continueImport: 'Continue import',
  appearanceAndLanguage: 'Appearance & language',
  theme: 'Theme',
  interfaceLanguage: 'Interface language',
  chinese: '中文',
  runtimeBehavior: 'Behavior',
  automaticRetry: 'Auto retry',
  retryAttempts: 'Retry attempts',
  autoPaste: 'Auto paste',
  autoPasteDescription: 'Wait about 600 ms, then paste back into the original app',
  launchAtStartup: 'Launch at startup',
  launchAsAdministrator: 'Administrator identity',
  launchAsAdministratorDescription: 'Windows requests UAC confirmation when saving; startup will use administrator privileges',
  screenshotArchive: 'Auto-archive screenshots',
  archiveDirectory: 'Archive directory',
  archiveDirectoryRequired: 'Choose an archive directory before enabling screenshot auto-archive',
  chooseDirectory: 'Choose directory',
  globalShortcuts: 'Global shortcuts',
  textTranslation: 'Text translation',
  screenshotTranslation: 'OCR translation',
  promptOptimization: 'Prompt optimization',
  recordTextTranslationShortcut: 'Record text translation shortcut',
  recordVisionShortcut: 'Record Vision shortcut',
  recordScreenshotShortcut: 'Record OCR translation shortcut',
  recordOptimizerShortcut: 'Record prompt optimizer shortcut',
  pressShortcut: 'Press shortcut',
  translationBehavior: 'Translation',
  sourceLanguage: 'Source language',
  targetLanguage: 'Target language',
  enableAiTranslation: 'Enable AI translation',
  aiModel: 'AI model',
  textTranslationAiModel: 'Text translation AI model',
  translationInterface: 'Translation service',
  aiTranslationSystemPrompt: 'AI translation system prompt',
  enableScreenshotTranslation: 'Enable OCR translation',
  screenshotTargetLanguage: 'OCR translation target language',
  screenshotSourceLanguage: 'OCR translation source language',
  enableAiOcr: 'Enable AI OCR',
  ocrModel: 'OCR model',
  ocrInterface: 'OCR service',
  aiVisionOcr: 'AI vision OCR',
  baiduOcr: 'Baidu OCR',
  chaoxingOcr: 'Chaoxing OCR',
  screenshotTranslationModel: 'OCR translation model',
  screenshotTranslationInterface: 'OCR translation service',
  translationModel: 'Translation model',
  showRecognizedSource: 'Show recognized source',
  streamingOutput: 'Streaming output',
  screenshotStreamingOutput: 'OCR translation streaming',
  showReasoning: 'Show reasoning',
  reasoningEffort: 'Reasoning effort',
  screenshotReasoningEffort: 'OCR translation reasoning effort',
  ocrPrompt: 'OCR prompt',
  screenshotTranslationPrompt: 'OCR translation prompt',
  credentialGroup: 'Service credentials',
  credentialSaved: 'Credentials saved securely',
  credentialRequired: 'Complete every credential field before saving',
  visionQa: 'Vision Q&A',
  enableVision: 'Enable Vision',
  responseLanguage: 'Response language',
  visionResponseLanguage: 'Vision response language',
  model: 'Model',
  visionModel: 'Vision model',
  visionStreamingOutput: 'Vision streaming output',
  visionReasoning: 'Show reasoning/summary',
  visionReasoningLabel: 'Show Vision reasoning/summary',
  visionReasoningEffort: 'Vision reasoning effort',
  webSearch: 'Web search',
  messageOrder: 'Message order',
  oldMessagesFirst: 'Old messages first',
  newMessagesFirst: 'New messages first',
  systemPrompt: 'System prompt',
  visionSystemPrompt: 'Vision system prompt',
  questionPrompt: 'Question prompt',
  visionQuestionPrompt: 'Vision question prompt',
  enableOptimizer: 'Enable optimizer',
  enablePromptOptimizer: 'Enable prompt optimizer',
  outputLanguage: 'Output language',
  optimizerOutputLanguage: 'Optimizer output language',
  optimizerModel: 'Prompt optimizer model',
  optimizerReasoningEffort: 'Prompt optimizer reasoning effort',
  optimizerSystemPrompt: 'Optimizer system prompt',
  optimizationPrompt: 'Optimization prompt',
  configurationManagement: 'Configuration',
  exportWithApiKeys: 'Include API keys in export',
  exportWithApiKeysDescription: 'Off by default; exported files contain sensitive data when enabled',
  exportIncludesApiKeys: 'Export API keys',
  exportConfiguration: 'Export configuration',
  importConfiguration: 'Import configuration',
  localOnlyFootnote: 'ScreenPilot stores settings and history metadata locally and has no account or cloud sync.',
  providersTitle: 'Model providers',
  providersDescription: 'Keys are stored in Windows Credential Manager, not in the settings file.',
  add: 'Add',
  noProviders: 'No model providers yet',
  noProvidersDescription: 'Add an OpenAI-compatible endpoint, then choose models for Translation, Vision, and Prompt.',
  unnamedProvider: 'Unnamed provider',
  name: 'Name',
  providerName: 'Provider name',
  providerBaseUrl: 'Provider Base URL',
  oneKeyPerLine: 'One key per line',
  fetchModels: 'Fetch models',
  modelsFetched: 'Fetched {count} models',
  connectionSucceeded: 'Connection succeeded',
  connectionFailed: 'Connection failed',
  testConnection: 'Test connection',
  deleteProvider: 'Delete {name}',
  manualModelName: '{name} manual model name',
  manualModelPlaceholder: 'Add a model manually, e.g. local:vision',
  addModel: 'Add',
  modelList: '{name} model list',
  savedKeyCount: '{count} keys stored securely',
  translatorTitle: 'Text Translation',
  translating: 'Translating…',
  submitShortcut: 'Ctrl+Enter to submit',
  waitingForInput: 'Waiting for input',
  translationHistory: 'Translation history',
  closeTranslator: 'Close translation',
  originalText: 'Original',
  translatorInputPlaceholder: 'Type text or press F2 to capture the current selection',
  resizeTranslationPanels: 'Resize original and translation panels',
  translatedText: 'Translation',
  copyTranslation: 'Copy translation',
  copyFailed: 'Copy failed. Check clipboard permissions',
  translatedTextPlaceholder: 'The translation appears here and can be edited',
  optimizerTitle: 'Prompt Optimizer',
  optimizing: 'Optimizing…',
  optimizeShortcut: 'Ctrl+Enter to optimize',
  optimizationHistory: 'Optimization history',
  closeOptimizer: 'Close optimizer',
  originalPrompt: 'Original prompt',
  optimize: 'Optimize',
  optimizerInputPlaceholder: 'Enter a prompt to optimize',
  resizeOptimizerPanels: 'Resize original prompt and result panels',
  optimizationResult: 'Optimized result',
  replaceOriginal: 'Replace original',
  copyOptimizationResult: 'Copy optimized result',
  optimizationResultPlaceholder: 'The optimized result can be edited here',
  historyCount: '{count} history items',
  historyEmpty: 'No history yet',
  deleteHistory: 'Delete history item',
  clearHistory: 'Clear',
  justNow: 'Just now',
  minutesAgo: '{count} min ago',
  hoursAgo: '{count} hr ago',
  daysAgo: '{count} days ago',
  copyCode: 'Copy code',
  send: 'Send',
  translationFailed: 'Translation failed',
  translatingToTarget: 'Translating to the target language…',
  duplicateProviderId: 'Provider IDs must be unique',
  providerHttpsRequired: 'Provider URLs must use HTTPS (except local addresses)',
  providerUrlInvalid: 'Provider URL is invalid',
  shortcutMissing: 'Shortcuts cannot be empty',
  shortcutConflict: 'Shortcuts conflict',
}

export const uiCopy: Record<InterfaceLanguage, UiCopy> = { zh, en }

export function copyFor(language: InterfaceLanguage | undefined): UiCopy {
  return uiCopy[language ?? 'zh']
}

export function formatCopy(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.split(`{${key}}`).join(String(value)),
    template,
  )
}

export function translationLanguageOptions(language: InterfaceLanguage, autoLabel: 'auto' | 'detect' = 'auto') {
  const t = copyFor(language)
  return [
    { value: 'auto' as TranslationLanguage, label: autoLabel === 'detect' ? t.autoDetect : t.auto },
    { value: 'zh-CN' as TranslationLanguage, label: t.simplifiedChinese },
    { value: 'en' as TranslationLanguage, label: t.english },
    { value: 'ja' as TranslationLanguage, label: t.japanese },
    { value: 'ko' as TranslationLanguage, label: t.korean },
  ]
}

export function translationMethodLabel(method: TranslationMethod, language: InterfaceLanguage): string {
  if (language === 'zh') {
    if (method === 'baidu') return '百度'
    if (method === 'tencent') return '腾讯'
    if (method === 'caiyun2') return '彩云小译 2'
    if (method === 'ai') return 'AI'
  } else {
    if (method === 'baidu') return 'Baidu'
    if (method === 'tencent') return 'Tencent'
    if (method === 'caiyun2') return 'Caiyun 2'
    if (method === 'ai') return 'AI'
  }
  const labels: Partial<Record<TranslationMethod, string>> = {
    google: 'Google',
    bing: 'Bing',
    bing2: 'Bing 2',
    yandex: 'Yandex',
    microsoft: 'Microsoft',
  }
  return labels[method] ?? method
}

export type { UiCopy }
